### ISSUE TITLE
Link house contribution to donations on admin side.

### ISSUE THREAD

**Issue by bvandermeer** [NPSC/HHK#29]

**Comment by ecrane57** [comment]
House contributions are not necessarily donations.  Anyway, how do you see this working?

**Comment by bvandermeer** [comment]
This was your idea.

I may have some details wrong but from what I remember: this came up when we were showing Saginaw how to create donation campaigns.  
When a guest over pays their visit, one option for that money is to donate it to the house.  But there's no way to link that money to an active campaign. And the donation shows up in a House report, but not a donations Admin side report. You were talking about how that should probably change.
Again, that's how I remember it.
