### ISSUE TITLE
Doctors Report counting differently

### ISSUE THREAD

**Issue by bvandermeer** [NPSC/HHK#39]
From email sent to Eric, subject: Testing .107

In the Doctors, Hospitals Report: The graph when you Run Here, looks like it includes patients that haven't been assigned a referral agent (or doctor).  There's a blank line.

But if you click on 'Only show patients without an assignment', it's a different number. There's 10 names vs the above's 2 next to the blank line:

It's as if a patient sometimes gets assigned someone named <blank> as a referral agent.  I don't know the best way to corroborate this, see how many patients there have been in total, and how the numbers add up.
The People Report doesn't give me the same numbers (some of the names above don't even show up)

**Comment by ecrane57** [comment]
Fixed. in build 110
