### ISSUE TITLE
Replace feature in Location lookup not working

### ISSUE THREAD

**Issue by bvandermeer** [NPSC/HHK#59]
In General Lookups --> Location, if you try to Replace the location with another, nothing seems to happen.

Carle has Peds listed twice, and they want to make sure all Peds 1 patients can be replaced by Peds 2, before deleting Peds 1. But nothing seems to happen when you hit the save button.

Trying it on Test Site, I couldn't get one Location to replace another.  Again, it seemed like the save button wasn't doing anything.

**Comment by ecrane57** [comment]
Click the delete box first
