### ISSUE TITLE
Calendar page filters

### ISSUE THREAD

**Issue by bvandermeer** [NPSC/HHK#8]
We already have a filter so show which hospital(s) are shown on the Calendar Page under the House Register page.
It would also be nice to have a control that shows just a specific block of rooms so we don’t have to scroll up and down the page.
Filters could also be created to show guests who need to pay, etc.

**Comment by ecrane57** [comment]
All done, build 120.  Now using room groups, a new feature of the new fullcalendar and scheduler tools.
